name: Terraform CI

on: [push, pull_request]

jobs:
  test:
    name: Terraform validate
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
      with:
        terraform_version: 0.12.29

    - run: terraform init -backend=false

    - run: terraform validate
